config/routes.rb
Rails.application.routes.draw do

root 'posts#index'
get 'about' => 'pages#about'

get '/getForm' => 'posts#getForm'
post '/postForm' => 'posts#postForm'
resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	 protect_from_forgery except: :new
	
	def index 
		@proj = Project.all
		@todos = Todo.all
	end

	def create
		#@todo1 = Todo.new(todos_params)

			@id_Category = params[:post1][:category]
			Rails.logger.info "Some debugging info #{@id_Category}"
			@text = params[:post1][:text]
			if @text != ''
				t = Todo.new(text: @text,isCompleted: false,id_project: @id_Category)
				t.save
				redirect_to root_url
			else 
				
				render html: "<script>alert('Введите задачу!')</script>".html_safe

			end
		
		
	end
	def postForm
		@todo_id = params[:id_todo]
		@todo_isCompleted = params[:todo_completed]
		todo_update = Todo.find(@todo_id )
		todo_update.isCompleted = @todo_isCompleted
		todo_update.save
		
		

	end
	def getForm
	end
	def show 
		
	end

	def new
		
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "main" %>
<html>

  <head>
  	
    <title>NewTestApp</title>
    
	<%= csrf_meta_tag %>
 <%= javascript_include_tag :jquery, :jquery_ujs %>
  </head>

  <body>
    <%= yield %>
    <script type="application/javascript">
            $(document).ready(function() { $(#selec).select2(); });
      </script>
   
  </body>

</html>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "main" %>

<div id="main">


<div id="AlertDiv"><h1>Задачи</h1>
	<%= link_to new_post_path,remote:true,id:"new_link2" do %>
   <%= image_tag "addTodoIcon.png", class: "image_class" %>
<% end %>
</div>

<div id="ab">
<% @proj.each do |product| %>  
<div id="showTodos">
	<h3><%= product.title %></h3> 
	<div id="line">
	</div>
   <dl>
	  <% @todos.where(id_project: product.id).each do |td| %>   
	  <%= link_to getForm_url, remote: true,:class => 'specific_service', 
        :data => {:id => td.id},:onclick => 
        "	var id = $(this).data('id');
        	
        	
        	var thisInput  = $(this).find('input[type=checkbox]');

        	var checked = thisInput.is(':checked');
        	thisInput[0].checked = (checked) ?  false : true;
        
        	var latDisplay = document.getElementById('id_todo');
        	latDisplay.value = id;
        	var latDisplay = document.getElementById('todo_completed');
        	latDisplay.value = (checked) ?  false : true;
        	$('#form_post_id').submit();" do %>
  		<div id="my-div">
		<%= form_for :article, url: postForm_url,:method=> 'post',remote:true, :html => {:id=>'form_post_id'}, class: "nifty_form" do |f| %>
				<%=hidden_field_tag :id_todo %>
				<%=hidden_field_tag :todo_completed %>
	  			<dd>
	  		
  				<div class="row"><input type="checkbox" value="<%=td.id %>" id="<%=td.id %>" disabled="true" > <span id="span"><%= td.text %></span></div>
  				</dd>
  				<% end %>
  				</div>
  				<script type="application/javascript">
	  				var isCompleted = <%=td.isCompleted%>;
	  				var overall = document.querySelector('input[id="<%=td.id %>"]');
					
	  				if  (isCompleted == true){
	  					overall.checked = true;
	  				} else {
	  					overall.checked = false;
	  				}

			</script>
  				<% end %>
  				<% end %>
	</dl>

	</div>

<% end %>   
</div>




<div id="without_button" style="display: none">
<h3>Новая задача</h3>
<div id="line2">
	</div>
<%= form_for :post1, url: posts_path,:method=> 'post', :html => {:id=>'form_id'} do |f| %>
	<%= f.text_field :text, placeholder: "Название задачи.." , class: 'text_field'%>
	
<%= f.collection_select(:category, Project.all, :id, :title, { include_blank: "Категория" }, { class: "select_categ",id:"selec" }) %>
	<p>
		<%= link_to "ОТМЕНА",posts_path, remote: true, id:"new_link"  %>
		
		<%= link_to 'ОК', "#", :onclick => "$('#form_id').submit()",id:"new_link_ok" %>
	
	</p>
	</div>
<% end %> 
<script type="application/javascript">
            $(document).ready(function() { 
            	$('.select_categ').select2();

            });
      </script>
</div>

app/views/posts/index.js.erb
$('#without_button').hide()

app/views/posts/new.js.erb
$('#without_button').show()

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
</p>